/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utp.misiontic2022.c2.p47.reto4.vista;

import javax.swing.JOptionPane;
import utp.misiontic2022.c2.p47.reto4.controlador.ControladorRequerimientos;

/**
 *
 * @author JPAM
 */
public class VistaRequerimientosGUI extends javax.swing.JFrame {

    private ControladorRequerimientos controlador;
    private ConsultaR1TM consultaR1TM;
    private ConsultaR2TM consultaR2TM;
    private ConsultaR3TM consultaR3TM;

    /**
     * Creates new form VistaRequerimientosGUI
     */
    public VistaRequerimientosGUI() {
        controlador = new ControladorRequerimientos();
        initComponents();
        listarConsulta1();
        listarConsulta2();
        listarConsulta3();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpPrincipal = new javax.swing.JTabbedPane();
        jRequerimiento1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTaR1 = new javax.swing.JTable();
        jRequerimiento2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTaR2 = new javax.swing.JTable();
        jRequerimiento3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTaR3 = new javax.swing.JTable();
        miMenu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenuItem();
        mVentanas = new javax.swing.JMenu();
        jC1 = new javax.swing.JMenuItem();
        jC2 = new javax.swing.JMenuItem();
        jC3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Requerimientos - Grupo 47 Ciclo 2 - Juan Pablo Aguirre Martínez");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jTaR1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTaR1);

        javax.swing.GroupLayout jRequerimiento1Layout = new javax.swing.GroupLayout(jRequerimiento1);
        jRequerimiento1.setLayout(jRequerimiento1Layout);
        jRequerimiento1Layout.setHorizontalGroup(
            jRequerimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jRequerimiento1Layout.setVerticalGroup(
            jRequerimiento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Requerimiento 1", jRequerimiento1);

        jTaR2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTaR2);

        javax.swing.GroupLayout jRequerimiento2Layout = new javax.swing.GroupLayout(jRequerimiento2);
        jRequerimiento2.setLayout(jRequerimiento2Layout);
        jRequerimiento2Layout.setHorizontalGroup(
            jRequerimiento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jRequerimiento2Layout.setVerticalGroup(
            jRequerimiento2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Requerimiento 2", jRequerimiento2);

        jTaR3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTaR3);

        javax.swing.GroupLayout jRequerimiento3Layout = new javax.swing.GroupLayout(jRequerimiento3);
        jRequerimiento3.setLayout(jRequerimiento3Layout);
        jRequerimiento3Layout.setHorizontalGroup(
            jRequerimiento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        jRequerimiento3Layout.setVerticalGroup(
            jRequerimiento3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        tpPrincipal.addTab("Requerimiento 3", jRequerimiento3);

        getContentPane().add(tpPrincipal, java.awt.BorderLayout.CENTER);

        mArchivo.setText("Archivo");

        jSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });
        mArchivo.add(jSalir);

        miMenu.add(mArchivo);

        mVentanas.setText("Ventanas");

        jC1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jC1.setText("Consulta Requerimiento 1");
        jC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC1ActionPerformed(evt);
            }
        });
        mVentanas.add(jC1);

        jC2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jC2.setText("Consulta Requerimiento 2");
        jC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC2ActionPerformed(evt);
            }
        });
        mVentanas.add(jC2);

        jC3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jC3.setText("Consulta Requerimiento 3");
        jC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jC3ActionPerformed(evt);
            }
        });
        mVentanas.add(jC3);

        miMenu.add(mVentanas);

        setJMenuBar(miMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC1ActionPerformed
        tpPrincipal.setSelectedIndex(0);
    }//GEN-LAST:event_jC1ActionPerformed

    private void jC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC2ActionPerformed
        tpPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_jC2ActionPerformed

    private void jC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jC3ActionPerformed
        tpPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_jC3ActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Desea cerrar la aplicación?", getTitle(), JOptionPane.YES_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRequerimientosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRequerimientosGUI().setVisible(true);
            }
        });
    }

    private void listarConsulta1() {
        try {
            var registrosBS = controlador.consultarRequerimiento1();
            consultaR1TM = new ConsultaR1TM(registrosBS);
            jTaR1.setModel(consultaR1TM);
        } catch (Exception e) {
        }
    }

    private void listarConsulta2() {
        try {
            var registrosBS2 = controlador.consultarRequerimiento2();
            consultaR2TM = new ConsultaR2TM(registrosBS2);
            jTaR2.setModel(consultaR2TM);
        } catch (Exception e) {
        }

    }

    private void listarConsulta3() {
        try {
            var registrosBS3 = controlador.consultarRequerimiento3();
            consultaR3TM = new ConsultaR3TM(registrosBS3);
            jTaR3.setModel(consultaR3TM);
        } catch (Exception e) {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jC1;
    private javax.swing.JMenuItem jC2;
    private javax.swing.JMenuItem jC3;
    private javax.swing.JPanel jRequerimiento1;
    private javax.swing.JPanel jRequerimiento2;
    private javax.swing.JPanel jRequerimiento3;
    private javax.swing.JMenuItem jSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTaR1;
    private javax.swing.JTable jTaR2;
    private javax.swing.JTable jTaR3;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mVentanas;
    private javax.swing.JMenuBar miMenu;
    private javax.swing.JTabbedPane tpPrincipal;
    // End of variables declaration//GEN-END:variables
}
